version: "3.8"

services:
  app:
    build:
      context: ../../
      dockerfile: infra/docker/Dockerfile
    env_file:
      - ../../.env
    volumes:
      - ../../:/var/www/html:ro
      - app_storage:/var/www/html/storage
    networks:
      - web

  nginx:
    image: nginx:1.25-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ../../:/var/www/html:ro
      - app_storage:/var/www/html/storage
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - web

  # db:
  #   image: postgres:16-alpine
  #   environment:
  #     POSTGRES_DB: myevents
  #     POSTGRES_USER: myevents
  #     POSTGRES_PASSWORD: change-me
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - web

volumes:
  app_storage:
  # pgdata:

networks:
  web:
    driver: bridge

